services:
  - type: web
    name: hote
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
